# 应用基本配置
spring:
  application:
    name: medical-data-service
  profiles:
    active: dev  # 默认激活开发环境

# 服务器配置
server:
  port: 8080
  servlet:
    context-path: /api

# 日志配置
logging:
  level:
    com.yourcompany: INFO
    org.springframework: WARN
#
## 共享数据库连接池配置
#spring:
#  datasource:
#    hikari:
#      maximum-pool-size: 10
#      minimum-idle: 5
#      connection-timeout: 30000
#      idle-timeout: 600000
#      max-lifetime: 1800000